/* 
	This file defines technologies that will be extracted from stream titles and then used to filter results. 
	Technologies with several common names can be expressed as an array, where the first item is the primary name of the technology.
*/

export default [
	["Vue", "VueJS"],
	["React", "ReactJS"],
	"React Native",
	"Svelte",
	["Angular", "AngularJS"],
	["JavaScript", "JS"],
	["Typescript", "TS"],
	"Java",
	"C",
	["C#", "c-sharp"],
	["C++", "cpp"],
	"Python",
	"Flask",
	"Django",
	"Bootstrap",
	"Azure",
	["Amazon Web Services", "AWS"],
	["Google Cloud Platform", "Google Cloud", "GCP"],
	"Rust",
	["Ruby on Rails", "Rails"],
	"MongoDB",
	["FaunaDB", "Fauna"],
	["GraphQL", "gql"],
	["NodeJS", "Node", "Node.js"],
	["Express", "ExpressJS", "Express.js"],
	["NextJS", "Next", "Next.js"],
	["PostgreSQL", "Postgres"],
	"MySQL",
	["Julia", "JuliaLang"],
	"Unity",
	["Unreal Engine", "Unreal", "UE4", "UE3", "UE2", "UE1", "UE"],
	"Godot",
	["NuxtJS", "Nuxt", "Nuxt.js"],
	["Gatsby", "GatsbyJS"],
	"AI",
	["HTML", "HTML5"],
	["CSS", "CSS3", "CSS2"],
	"PHP",
	"Laravel",
	"Dart",
	"Flutter",
	"Erlang",
	"Elixir",
	"Kotlin",
	"Phoenix"
]